/* 50 daily expressions (korean - english) */
window.KB_DAILY = [
 {k:"안녕하세요", e:"Hello"},
 {k:"좋은 아침이에요", e:"Good morning"},
 {k:"잘 자요", e:"Good night"},
 {k:"감사합니다", e:"Thank you"},
 {k:"천만에요", e:"You're welcome"},
 {k:"죄송합니다", e:"Sorry"},
 {k:"괜찮아요", e:"It's okay"},
 {k:"사랑해요", e:"I love you"},
 {k:"배고파요", e:"I'm hungry"},
 {k:"목말라요", e:"I'm thirsty"},
 {k:"피곤해요", e:"I'm tired"},
 {k:"화장실 가고 싶어요", e:"I need to go to the bathroom"},
 {k:"몇 시예요?", e:"What time is it?"},
 {k:"도와주세요", e:"Help me"},
 {k:"천천히 말해 주세요", e:"Please speak slowly"},
 {k:"다시 말해 주세요", e:"Please say it again"},
 {k:"이해했어요", e:"I understand"},
 {k:"이해하지 못했어요", e:"I don't understand"},
 {k:"어디에요?", e:"Where is it?"},
 {k:"얼마예요?", e:"How much is it?"},
 {k:"괜찮습니다", e:"No problem"},
 {k:"축하합니다", e:"Congratulations"},
 {k:"힘내세요", e:"Cheer up / Stay strong"},
 {k:"조심하세요", e:"Be careful"},
 {k:"잘 했어요", e:"Well done"},
 {k:"맛있어요", e:"It's delicious"},
 {k:"배불러요", e:"I'm full"},
 {k:"늦어서 죄송해요", e:"Sorry I'm late"},
 {k:"오늘 날씨 어때요?", e:"How's the weather today?"},
 {k:"맛있게 드세요", e:"Enjoy your meal"},
 {k:"생일 축하해요", e:"Happy Birthday"},
 {k:"잘 다녀오세요", e:"Have a good trip"},
 {k:"조용히 해 주세요", e:"Please be quiet"},
 {k:"문을 닫아 주세요", e:"Please close the door"},
 {k:"문을 열어 주세요", e:"Please open the door"},
 {k:"전화해 주세요", e:"Please call me"},
 {k:"기다려 주세요", e:"Please wait"},
 {k:"바쁘세요?", e:"Are you busy?"},
 {k:"천천히 드세요", e:"Eat slowly"},
 {k:"사진 촬영 금지", e:"No photography"},
 {k:"금연", e:"No smoking"},
 {k:"도착했습니다", e:"I have arrived"},
 {k:"출발합니다", e:"We are departing"},
 {k:"예약되어 있나요?", e:"Is it reserved?"},
 {k:"표를 보여 주세요", e:"Please show your ticket"},
 {k:"다음에 봐요", e:"See you next time"},
 {k:"잘 부탁드립니다", e:"Please take care of me / nice to meet you"},
 {k:"행복하세요", e:"Be happy"}
];
