// === Native Korean Numbers ===
export const nativeNumbers = [
  { korean: "하나", english: "one" },
  { korean: "둘", english: "two" },
  { korean: "셋", english: "three" },
  { korean: "넷", english: "four" },
  { korean: "다섯", english: "five" },
  { korean: "여섯", english: "six" },
  { korean: "일곱", english: "seven" },
  { korean: "여덟", english: "eight" },
  { korean: "아홉", english: "nine" },
  { korean: "열", english: "ten" },
  { korean: "열하나", english: "eleven" },
  { korean: "열둘", english: "twelve" },
  { korean: "열셋", english: "thirteen" },
  { korean: "열넷", english: "fourteen" },
  { korean: "열다섯", english: "fifteen" },
  { korean: "열여섯", english: "sixteen" },
  { korean: "열일곱", english: "seventeen" },
  { korean: "열여덟", english: "eighteen" },
  { korean: "열아홉", english: "nineteen" },
  { korean: "스물", english: "twenty" },
  { korean: "서른", english: "thirty" },
  { korean: "마흔", english: "forty" },
  { korean: "쉰", english: "fifty" },
  { korean: "예순", english: "sixty" },
  { korean: "일흔", english: "seventy" },
  { korean: "여든", english: "eighty" },
  { korean: "아흔", english: "ninety" }
];

// === Sino-Korean Numbers ===
export const sinoNumbers = [
  { korean: "일", english: "one" },
  { korean: "이", english: "two" },
  { korean: "삼", english: "three" },
  { korean: "사", english: "four" },
  { korean: "오", english: "five" },
  { korean: "육", english: "six" },
  { korean: "칠", english: "seven" },
  { korean: "팔", english: "eight" },
  { korean: "구", english: "nine" },
  { korean: "십", english: "ten" },
  { korean: "백", english: "hundred" },
  { korean: "천", english: "thousand" },
  { korean: "만", english: "ten thousand" },
  { korean: "십만", english: "hundred thousand" },
  { korean: "백만", english: "one million" },
  { korean: "천만", english: "ten million" },
  { korean: "억", english: "hundred million" },
  { korean: "십억", english: "billion" },
  { korean: "백억", english: "ten billion" },
  { korean: "천억", english: "hundred billion" },
  { korean: "조", english: "trillion" }
];
