/* 50 travel phrases (korean - english) */
window.KB_TRAVEL = [
 {k:"영수증 주세요", e:"Please give me a receipt"},
 {k:"포장해 주세요", e:"Please make it takeaway"},
 {k:"이곳은 어디예요?", e:"Where is this place?"},
 {k:"병원이 어디에요?", e:"Where is the hospital?"},
 {k:"화장실 어디예요?", e:"Where is the restroom?"},
 {k:"이것 얼마예요?", e:"How much is this?"},
 {k:"카드 돼요?", e:"Do you accept card?"},
 {k:"현금만 돼요", e:"Cash only"},
 {k:"추천해 주세요", e:"Please recommend something"},
 {k:"메뉴 영어로 있어요?", e:"Is the menu in English?"},
 {k:"예약했어요", e:"I have a reservation"},
 {k:"택시 불러 주세요", e:"Please call a taxi"},
 {k:"공항까지 가주세요", e:"Please take me to the airport"},
 {k:"문 닫았어요?", e:"Is it closed?"},
 {k:"열려 있나요?", e:"Is it open?"},
 {k:"도와주세요", e:"Help me"},
 {k:"죄송합니다, 길을 잃었어요", e:"Sorry, I'm lost"},
 {k:"영어 할 수 있어요?", e:"Can you speak English?"},
 {k:"사진 찍어 주세요", e:"Please take a photo"},
 {k:"사진 찍어 드릴까요?", e:"Shall I take your photo?"},
 {k:"왼쪽이에요", e:"It's on the left"},
 {k:"오른쪽이에요", e:"It's on the right"},
 {k:"똑바로 가세요", e:"Go straight"},
 {k:"언제 출발하나요?", e:"When does it depart?"},
 {k:"몇 시에 도착하나요?", e:"What time does it arrive?"},
 {k:"표 한 장 주세요", e:"Please give me one ticket"},
 {k:"예약 확인해 주세요", e:"Please confirm the reservation"},
 {k:"짐 보관소 있나요?", e:"Is there a baggage storage?"},
 {k:"짐을 잃어버렸어요", e:"I lost my luggage"},
 {k:"무료 와이파이 있어요?", e:"Is there free Wi-Fi?"},
 {k:"와이파이 비밀번호가 뭐예요?", e:"What's the Wi-Fi password?"},
 {k:"물 한 잔 주세요", e:"Please give me a glass of water"},
 {k:"메뉴 추천해 주세요", e:"Please recommend a dish"},
 {k:"채식 메뉴 있어요?", e:"Do you have vegetarian options?"},
 {k:"계산서 부탁해요", e:"Could I have the bill?"}, 
 {k:"다음 정류장은 어디예요?", e:"What is the next stop?"}, 
 {k:"좌석 예약 되었나요?", e:"Is my seat reserved?"}, 
 {k:"창가 좌석 주세요", e:"Window seat please"}, 
 {k:"복도 좌석 주세요", e:"Aisle seat please"}, 
 {k:"무릎 공간이 넉넉한 좌석 주세요", e:"Seat with more legroom please"}, 
 {k:"안전벨트 착용하세요", e:"Please fasten your seatbelt"}, 
 {k:"짐을 위에 올려주세요", e:"Please put the luggage above"}, 
 {k:"도착 전에 알려 주세요", e:"Please notify me before arrival"}, 
 {k:"짐 무게가 얼마예요?", e:"How much does the luggage weigh?"}, 
 {k:"환전 어디서 하나요?", e:"Where can I exchange money?"}, 
 {k:"영수증을 분실했어요", e:"I lost the receipt"}
];
